### ISSUE TITLE
Merge Snap Camera into build chain

### ISSUE THREAD

**Issue by janengelmohr** [visi0nary/android_device_alps_k05ts_a#76]
It nearly works already with https://github.com/visi0nary/android_packages_apps_Snap but once a picture is taken, the preview freezes... Camera2 works fine though so I am sure the callback needs to be changed in the app.

**Comment by janengelmohr** [comment]
```
> E/MtkCam/Cam1Device(  274): (274)(Default:0)[Cam1DeviceBase::takePicture] CamAdapter->takePicture() returns: [Function not implemented(38)] (takePicture){#858:vendor/mediatek/proprietary/hardware/mtkcam/v1/device/Cam1DeviceBase.cpp}
> E/CAM_AndroidCameraManagerImpl( 5520): take picture failed.
> E/AndroidRuntime( 5520): FATAL EXCEPTION: Camera Handler Thread
> E/AndroidRuntime( 5520): Process: org.cyanogenmod.snap, PID: 5520
> E/AndroidRuntime( 5520): java.lang.RuntimeException: takePicture failed
> E/AndroidRuntime( 5520):  at android.hardware.Camera.native_takePicture(Native Method)
> E/AndroidRuntime( 5520):  at android.hardware.Camera.takePicture(Camera.java:1501)
> E/AndroidRuntime( 5520):  at com.android.camera.AndroidCameraManagerImpl$CameraHandler$1.run(AndroidCameraManagerImpl.java:165)
> E/AndroidRuntime( 5520):  at android.os.Handler.handleCallback(Handler.java:739)
> E/AndroidRuntime( 5520):  at android.os.Handler.dispatchMessage(Handler.java:95)
> E/AndroidRuntime( 5520):  at android.os.Looper.loop(Looper.java:135)
> E/AndroidRuntime( 5520):  at android.os.HandlerThread.run(HandlerThread.java:61)
```

This happened after pushing the "Take Picture" button again when the old image was shown.

**Comment by valascus** [comment]
If u select HDR, camera doesnt freeze

**Comment by janengelmohr** [comment]
Good finding, thank you!

**Comment by janengelmohr** [comment]
fixed with https://github.com/visi0nary/android_device_elephone_p8000/commit/a0971122e5248891c384649da916698ceec4b2a4
